### ISSUE TITLE
Actualizar head title de página principal

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/hackathon2018#3]
![imagen](https://user-images.githubusercontent.com/11017088/47966790-cdd68f00-e056-11e8-8d5c-a6bf7231a968.png)

Que la pestaña se llama Evento 2016 en vez de Hackatón

**Comment by jgvictores** [comment]
Actualizado vía 4544cbdc187cbcee6c87b82968783626eb18efb1, mejorado vía 00b2ca66fe4da3627b033bc9c6f91c0651002b8e
